# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-03 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('telephone', models.CharField(max_length=10)),
                ('bureau', models.CharField(max_length=200)),
                ('batiment', models.CharField(choices=[('GeePs', 'GeePs'), ('Breguet', 'Breguet')], max_length=10)),
                ('matlabRelease', models.CharField(choices=[('R2017b', 'R2017b'), ('R2016b', 'R2016b'), ('R2015b', 'R2015b'), ('R2014b', 'R2014b'), ('R2013b', 'R2013b')], max_length=10)),
                ('operatingSystem', models.CharField(choices=[('Windows', 'Windows'), ('MacOS', 'MacOS'), ('Linux', 'Linux')], max_length=10)),
                ('hostID', models.IntegerField()),
            ],
        ),
    ]
